pipeline {
    //agent {
    //    docker {
    //        image 'maven:3.9.0'
    //        args '-v /root/.m2:/root/.m2'
    //    }
    //}
    tools {
        maven 'm3' // This is the name you gave to your Maven installation in Global Tool Configuration
    }
    parameters {
        string(name: 'ENVIRONMENT', defaultValue: 'dev', description: 'Environment to deploy to')
        booleanParam(name: 'RUN_TESTS', defaultValue: true, description: 'Whether to run tests')
        choice(name: 'DEPLOYMENT_SERVER', choices: ['staging', 'production'], description: 'Choose the deployment server')
    }
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                echo "hello c1"
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
