pipeline {
    //agent {
    //    docker {
    //        image 'maven:3.9.0'
    //        args '-v /root/.m2:/root/.m2'
    //    }
    //}
    tools {
        maven 'm3' // This is the name you gave to your Maven installation in Global Tool Configuration
    }

    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                echo "hello c1"
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
